### ISSUE TITLE
PEM cert with passphrase

### ISSUE THREAD

**Issue by recipedude** [alloy/lowdown#10]
Using a PEM certificate with a passphrase results in:

TypeError - no implicit conversion of Hash into String:
  lowdown (0.2.0) lib/lowdown/certificate.rb:34:in `initialize'
  lowdown (0.2.0) lib/lowdown/certificate.rb:34:in `new'
  lowdown (0.2.0) lib/lowdown/certificate.rb:34:in `from_pem_data'
  lowdown (0.2.0) lib/lowdown/certificate.rb:19:in `certificate'

Appears as if there's no way to initialize a Lowdown::Client using a certificate with a passphrase.  Although there seems to be passphrase support in lib/lowdown/certificate.rb.  Just no way to pass in the parameter.

**Comment by alloy** [comment]
You should be able to create a Certificate and pass that to the Client constructor. E.g.:

```ruby
certificate = Lowdown::Certificate.from_pem_data(data, passphrase)
Lowdown::Client.production(true, certificate: certificate, ...)
```

**Comment by alloy** [comment]
Please re-open if this doesn’t work for you.
