### ISSUE TITLE
Apple feedback service

### ISSUE THREAD

**Issue by mayank-singh** [alloy/lowdown#17]
Is there any option provided to  fetch the current list of those devices that have repeatedly reported failed-delivery attempts?

We can access the production feedback service via feedback.push.apple.com on port 2196 and the development feedback service via feedback.sandbox.push.apple.com on port 2196.

**Comment by alloy** [comment]
There’s no feedback service anymore with the HTTP/2 provider API. Instead you get the feedback for each individual HTTP/2 request.
