### ISSUE TITLE
TopicDisAllow

### ISSUE THREAD

**Issue by rayway30419** [alloy/lowdown#23]
Hi alloy,

After I user the certificate to establish a lowdown client, 

the client's default_topic shows "!xxxxxx". ( '!' + bundle id )

Then when I send push notifications to devices, apns response me 400 with reason "TopicDisallowed".

It happens to 5/32 apps.

Do you have any idea?

**Comment by alloy** [comment]
That probably means that [the topics field](https://github.com/alloy/lowdown/blob/e22e28099846bd7ed41a37405fc2e84605599aa9/lib/lowdown/certificate.rb#L127-L134) of the certificate may contain other values than [I expected](https://github.com/alloy/lowdown/blob/e22e28099846bd7ed41a37405fc2e84605599aa9/test/certificate_test.rb#L63-L68).

Care to make a PR for the format that your certificate holds?

**Comment by rayway30419** [comment]
May I send my certificate by email?

**Comment by rayway30419** [comment]
I find the others certifications topic is "$ + bundle_id"

**Comment by alloy** [comment]
You don’t need to send me your certificate, you can check the value yourself like so:

```
$ irb -r openssl
irb(main):001:0> cert = OpenSSL::X509::Certificate.new(File.read('/path/to/certificate.pem')); nil
=> nil
irb(main):002:0> cert.extensions.find { |ext| ext.oid == '1.2.840.113635.100.6.3.6' }.value
=> "0d..net.artsy.artsy0...app..net.artsy.artsy.voip0...voip..net.artsy.artsy.complication0...complication"
```

**Comment by rayway30419** [comment]
I got 

`"0...!com.kdanmobile.ipad.pdfreaderlite0...app.&com.kdanmobile.ipad.pdfreaderlite.voip0...voip..com.kdanmobile.ipad.pdfreaderlite.complication0...complication"`

and lowdown default_topic

`@default_topic="!com.kdanmobile.ipad.pdfreaderlite" 
`

**Comment by alloy** [comment]
Interesting, well it’s definitely clear where those `!` and `&` characters are coming in from. I’m still not sure what they signify and feel like I might be overlooking a proper parser for the format of this value 🤔

But for now it should be easy enough for you to make a PR that adds entries formatted like yours to [the tests](https://github.com/alloy/lowdown/blob/e22e28099846bd7ed41a37405fc2e84605599aa9/test/certificate_test.rb#L63-L68) and then make the parsing work for both cases.

**Comment by rayway30419** [comment]
I thought it is not easy for me, but I will give it a try. :(

**Comment by rayway30419** [comment]
Hi @alloy,

I found this situation occurs in other certificates, too.

If this parser is only want to grep the bundle id, why not just parse the subject? :(

**Comment by alloy** [comment]
@rayway30419 The reason that it’s not _just_ the bundle ID is that a universal certificate may be used for more than 1 purpose. I pushed a fix that should be the _right_ fix, let me know if it works for you.

**Comment by rayway30419** [comment]
Hi @alloy 
The fix by ASN1 looks well.
I thought you can commit this modification into rubygems. :)
thx

**Comment by sposinff** [comment]
Has this fix been released?  We are experiencing this error (only in one of our apps).

**Comment by mikekavouras** [comment]
@alloy can confirm that this is fixed on master, but it doesn't look like it's been released. Fetching from rubygems.org still has the bug.

**Comment by alloy** [comment]
Hey, just got back from holiday.

My bad, I’ll put out a release this week. Thanks for reminding me.
