### ISSUE TITLE
We are getting "Actor crashed! - ArgumentError: this IO is already registered with selector" exception when using a persistent connection

### ISSUE THREAD

**Issue by amitsaxena** [alloy/lowdown#25]
We are using a keep_alive: true connection, and seeing the following exceptions in production:

[APNS Connection#0x7f420591c910] Connecting...
[APNS Connection#0x7f420591c910] Connection established.
Actor crashed!
ArgumentError: this IO is already registered with selector
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/reactor.rb:42:in `register'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/reactor.rb:42:in `wait'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/reactor.rb:26:in `wait_writable'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io.rb:66:in `wait_writable'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:34:in `wait_writable'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:64:in `rescue in block in syswrite'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:61:in `block in syswrite'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:390:in `synchronize'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:59:in `syswrite'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:356:in `do_write'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:287:in `print'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/lowdown-0.3.2/lib/lowdown/connection.rb:182:in `block in connect!'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/emitter.rb:34:in `block in emit'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/emitter.rb:33:in `delete_if'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/emitter.rb:33:in `emit'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/flow_buffer.rb:56:in `block in send_data'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/flow_buffer.rb:56:in `each'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/flow_buffer.rb:56:in `send_data'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/connection.rb:346:in `send'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/client.rb:38:in `send'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/emitter.rb:34:in `block in emit'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/emitter.rb:33:in `delete_if'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/emitter.rb:33:in `emit'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/flow_buffer.rb:56:in `block in send_data'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/flow_buffer.rb:56:in `each'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/flow_buffer.rb:56:in `send_data'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/stream.rb:136:in `send'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/stream.rb:192:in `data'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/lowdown-0.3.2/lib/lowdown/connection.rb:375:in `try_to_perform_request!'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/lowdown-0.3.2/lib/lowdown/connection.rb:326:in `request'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/lowdown-0.3.2/lib/lowdown/connection.rb:312:in `post'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/var/www/apps/push_app/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
[APNS Connection#0x7f420591c910] Closing...
[APNS Connection#0x7f4208d0d760] Connecting...
[APNS Connection#0x7f41dd75f280] Connecting...
[APNS Connection#0x7f41dd75f280] Connection established.
[APNS Connection#0x7f4208d0d760] Connection established.

**Comment by alloy** [comment]
Closing for now due to lack of actionable data, feel free to re-open if you have more info.
