### ISSUE TITLE
[very low priority] doesn't work with spring and Rails 4.2.5

### ISSUE THREAD

**Issue by snow** [alloy/lowdown#9]
In development environment with spring enabled, either in console or sidekiq worker, 
```ruby
client = Lowdown::Client.production false, certificate: File.read('/path/to/apple_push_notification.pem')`
```
will get error message "fatal: No live threads left. Deadlock?"
When exiting console, will get message "Couldn't cleanly terminate all actors in 10 seconds!"

it works fine without spring.

**Comment by alloy** [comment]
Thanks for the heads-up! Spring apparently makes use of `Process.fork`, so the same ‘gotcha’ applies as described in the [README](https://github.com/alloy/lowdown#gotchas). I’ll list Spring there as a know tool that forks. 

PS: What version of Sidekiq are you using, >= 4?

**Comment by snow** [comment]
it's Sidekiq 4.0.1

**Comment by alloy** [comment]
Pushed https://github.com/alloy/lowdown/commit/aa7424e2b82c3ac2d18ed192519885ed7531b0ff. Seems good enough?

**Comment by snow** [comment]
well, this issue happens when when creating Lowdown::Client instance outside Rails initializer, e.g. in Rails console.

So for now, I think it's better to suggest user to remove Spring completely for now.

**Comment by nextofsearch** [comment]
I agree with @snow. I wasted more than 2 hours because of this issue.

**Comment by alloy** [comment]
I’m fine with suggesting that 👍 but please suggest better README changes via a PR.

**Comment by snow** [comment]
here it comes https://github.com/alloy/lowdown/pull/22
